In [1]:
# Try your first Python output

print('Hello, Python!')

Hello, Python!


In [3]:
# Practice on writing comments

print('Hello, Python!') # This line prints a string
# print('Hi')

Hello, Python!


In [2]:
# Check the Python Version

import sys
print(sys.version)

3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]


In [7]:
# Convert integer 2 to a float and check its type
type(float(2))

# Convert True to int
int(True)

1

In [9]:
import numpy as np
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [10]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [11]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])